name: CI

on: [push, pull_request]

env:
  GO_VERSION: '1.18.0-rc1' # '^1.18'
  GO_STABLE: 'false' # 'true'

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - run: go get ./...
      - run: go test ./...